### ISSUE TITLE
Todo-Co/003: Corrections d'anomalies

### ISSUE THREAD

**Issue by PavelKlimovich** [PavelKlimovich/ToDo-Co#4]
**Une tâche doit être attachée à un utilisateur**

- [x] Actuellement, lorsqu’une tâche est créée, elle n’est pas rattachée à un utilisateur. Il vous est demandé d’apporter les corrections nécessaires afin qu’automatiquement, à la sauvegarde de la tâche, l’utilisateur authentifié soit rattaché à la tâche nouvellement créée.

Lors de la modification de la tâche, l’auteur ne peut pas être modifié.

Pour les tâches déjà créées, il faut qu’elles soient rattachées à un utilisateur “anonyme”.

**Choisir un rôle pour un utilisateur**

- [x] Lors de la création d’un utilisateur, il doit être possible de choisir un rôle pour celui-ci. Les rôles listés sont les suivants :

rôle utilisateur (ROLE_USER) ;
rôle administrateur (ROLE_ADMIN).

- [x] Lors de la modification d’un utilisateur, il est également possible de changer le rôle d’un utilisateur.

**Implémentation de nouvelles fonctionnalités**
Autorisation

- [x] Seuls les utilisateurs ayant le rôle administrateur (ROLE_ADMIN) doivent pouvoir accéder aux pages de gestion des utilisateurs.

- [x] Les tâches ne peuvent être supprimées que par les utilisateurs ayant créé les tâches en question.

- [x] Les tâches rattachées à l’utilisateur “anonyme” peuvent être supprimées uniquement par les utilisateurs ayant le rôle administrateur (ROLE_ADMIN).
